# Generated by Django 2.1.1 on 2018-10-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorbases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, max_length=255, null=True)),
                ('esquema', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='base',
            name='atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de atualizacao'),
        ),
        migrations.AddField(
            model_name='tabela',
            name='base',
            field=models.ForeignKey(choices=[(3, 'CONTROLE_BASES_ODP'), (4, 'NOVABASE'), (2, 'BASE_TESTE_ASASASASAS_TTT')], on_delete=django.db.models.deletion.CASCADE, to='gestorbases.Base'),
        ),
    ]
