# Generated by Django 2.1.1 on 2018-10-08 11:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gestorbases', '0002_auto_20181004_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atualizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateField(auto_now_add=True, verbose_name='Data da atualizacao')),
                ('responsavel', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('mes_ref', models.IntegerField(blank=True, null=True)),
                ('ano_ref', models.IntegerField(blank=True, null=True)),
                ('origem_dados', models.CharField(max_length=255)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tabela',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='tabela',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorbases.Base'),
        ),
        migrations.AddField(
            model_name='atualizacao',
            name='tabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorbases.Tabela'),
        ),
    ]
