# Generated by Django 2.1.1 on 2018-10-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorbases', '0004_auto_20181017_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
