# Generated by Django 2.1.1 on 2018-09-28 12:26

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('seq_geral', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'alunos',
                'managed': True,
            },
            managers=[
                ('alunos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('persons', django.db.models.manager.Manager()),
            ],
        ),
    ]
