# Generated by Django 2.1.1 on 2018-10-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alunos',
        ),
    ]
